#No database connection
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# NOTE: #####################################################################################
# I disabled my connection settings for the MySQL database so that there is no problem.

# #MySQL Database
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/fan
#     username: root
#     password: 1234
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL5Dialect

# #Port number
# server:
#   port: 5000

# #Log location
# logging:
#   file:
#     name: C:/logs/fan.log
